### ISSUE TITLE
fs error on temp directory when running tapedeck

### ISSUE THREAD

**Issue by nexussays** [juliangruber/tapedeck#8]
I'm getting the following error when running tapedeck.

```
fs.js:647
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'C:\tmp\4a49d8dd'
  at Object.fs.mkdirSync (fs.js:647:18)
  at Object.<anonymous> (C:\Users\nexus\AppData\Roaming\npm\node_modules\tapedeck\index.js:39:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by juliangruber** [comment]
can you try 0.3.5?

**Comment by nexussays** [comment]
No longer throws that error, but it appears to just hang when run with phantom, and getting a permission error in Travis: https://travis-ci.org/nexussays/load.js/builds/35767512

**Comment by juliangruber** [comment]
ok, change of plans :D try

``` bash
$ npm install -g browserify tape-run
$ browserify test/*.js | tape-run
```

i'm not sure how pipes work in whindows shells though

**Comment by nexussays** [comment]
```
$ browserify test/*.js | tape-run
Error: Cannot find module 'C:\Users\nexus\Development\Projects\Libraries\load.js\test\*.js' from 'C:\Users\nexus\Development\Projects\Libraries\load.js'
    at C:\Users\nexus\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:42:25
    at load (C:\Users\nexus\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:60:43)
    at C:\Users\nexus\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:66:22
    at C:\Users\nexus\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:21:47
    at Object.oncomplete (fs.js:107:15)
no matches for phantom/*
```

Same results in cmd, powershell, and gitbash.

I already have a browserify-d testing bundle, how else can I pass it to tape-run?

**Comment by juliangruber** [comment]
``` bash
cat "location-of-bundle" | tape-run
```

**Comment by nexussays** [comment]
```
$ cat test/test-bundled.js | tape-run
no matches for phantom/*
```

**Comment by juliangruber** [comment]
ok, try installing phantomjs on your machine, or pass `-b chrome` to tape-run

**Comment by nexussays** [comment]
That helped :smile:

So it appears to be working at a system level, but my given use-case seems to not work. I have a single browserify bundle for the tests but they still need the directory structure to load other files and it seems the webserver tape-run spins up is isolated.
